name: Build node-chrome

on: workflow_dispatch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: avhb/node-chrome-av # ${{ github.repository }}

jobs:
  build-node-chrome:
    runs-on: ubuntu-22.04
    name: Build and Push to ghcr.io
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: set up ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg

      - name: Generate media files
        run: ./generate-media-files.sh

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} 

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./build
          file: ./build/dockerfile-chrome
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}